version: "3.9"

name: "jenkins-inbound-agent"

services:

  server:
    image: localhost:5000/sut
    build:
      context: .
      dockerfile: Dockerfile

  sut:
    image: alpine:3.17
    depends_on:
      - server
    entrypoint: ""
    command: >-
      /bin/sh -c '
      echo "Todo"
      '
