---

name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
  # allow external contributions to use secrets within trusted code
  # pull_request_target:
  #   types: [opened, synchronize, closed]
  #   branches:
  #     - "main"
  #     - "master"
  push:
    tags:
      - v*.*.*

jobs:
  flowzone:
    name: Flowzone
    # uses: product-os/flowzone/.github/workflows/flowzone.yml@v0.54.0
    uses: issenn/flowzone/.github/workflows/flowzone.yml@v0.54.0
    # prevent duplicate workflows and only allow one `pull_request` or `pull_request_target` for
    # internal or external contributions respectively
    if: |
      (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request') ||
      (github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request_target') ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    secrets:
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN || github.token }}
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      # Disable branch protection updates whilst testing flowzone, remove before merging
      protect_branch: false
      disable_versioning: true
      docker_images: |
        ghcr.io/issenn/jenkins-inbound-agent,
        docker.io/issenn/jenkins-inbound-agent
      restrict_custom_actions: false
